spring:
  application:
    name: semiperm-backend

  profiles:
    active: local
    group:
      local: db, oauth
      prod: db, oauth
      test: db, oauth

logging:
  level:
    org.hibernate:
      SQL: debug
      type: trace

---
spring:
  config:
    activate:
      on-profile: test
logging:
  level:
    org.hibernate:
      SQL: debug
      type: trace

---
spring:
  config:
    activate:
      on-profile: prod
logging:
  level:
    org.hibernate:
      SQL: error
