# default: local
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/SemipermDB?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  jpa:
    defer-datasource-initialization: false #true
    hibernate:
      ddl-auto: none #create
#  sql:
#    init:
#      mode: always

---
spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:mysql://34.64.96.216:3306/SemipermDB?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
  sql:
    init:
      mode: always


---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:mysql://34.64.96.216:3306/SemipermDB?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
  jpa:
    defer-datasource-initialization: false
    hibernate:
      ddl-auto: none
  sql:
    init:
      mode: never