spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/SemipermDB?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: semiperm
    password: semiperm123

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none
#      ddl-auto: create  # test
    #      ddl-auto: none when prod is released
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always